using System.Collections.Generic;
using OutpostZero.Core;

namespace OutpostZero.Shell
{
    public static class Loc
    {
        private static readonly Dictionary<string, string> english = new Dictionary<string, string>
        {
            { "hud.expedition", "OUTPOST ZERO — EXPEDITION" },
            { "hud.health", "Health" },
            { "hud.stamina", "Stamina" },
            { "hud.extract", "Reach the sanctuary gate to extract" },
            { "menu.pause", "PAUSED" },
            { "menu.resume", "Resume" },
            { "menu.save", "Save" },
            { "menu.camp", "Sanctuary" },
            { "menu.settings", "Settings" },
            { "menu.main", "Main Menu" },
            { "menu.codex", "Codex" },
            { "menu.skip", "Skip the lesson" },
            { "menu.restart", "Restart" },
            { "menu.leader", "LEADER KILLED" },
            { "menu.choose", "Choose who walks out at dawn." },
            { "menu.falls", "The outpost falls" },
            { "menu.holds", "OUTPOST HOLDS" },
            { "menu.broadcast", "The broadcast went out. The gate can stay shut." },
            { "menu.enter", "Enter sanctuary" },
            { "menu.endless", "Keep the nights" },
            { "menu.new", "New outpost" },
            { "menu.air", "The tower is on the air." },
            { "menu.supplies", "Supplies are back inside the gate." },
            { "menu.next", "Next:" },
            { "menu.names", "names on the memorial wall." },
            { "menu.names_none", "Every name on the roster is gone." },
            { "menu.credits", "CREDITS" },
            { "menu.brand", "Outpost Zero" },
            { "menu.blurb", "A sanctuary, a street, and whoever is still on the board." },
            { "menu.back", "Back" },
            { "menu.title", "OUTPOST ZERO" },
            { "menu.version", "Version" },
            { "menu.continue", "Continue" },
            { "menu.saves", "Saves" },
            { "menu.street", "Back to the street" },
            { "menu.board", "Local board" },
            { "menu.board_empty", "No finished runs yet." },
            { "camp.title", "SANCTUARY" },
            { "result.title", "EXPEDITION COMPLETE" },
            { "gameover.title", "THE OUTPOST FALLS" },
            { "diff.scavenger", "Scavenger" },
            { "diff.survivor", "Survivor" },
            { "diff.nightmare", "Nightmare" },
            { "set.title", "SETTINGS" },
            { "set.shake", "Shake" },
            { "set.volume", "Volume" },
            { "set.effects", "Effects" },
            { "set.music", "Music" },
            { "set.ambience", "Ambience" },
            { "set.ui", "Interface" },
            { "set.fov", "Field of view" },
            { "set.text", "Text" },
            { "set.hud", "HUD" },
            { "set.bright", "Brightness" },
            { "set.subs_on", "Subtitles on" },
            { "set.subs_off", "Subtitles off" },
            { "set.color", "Colorblind mode" },
            { "set.quality", "Quality:" },
            { "set.tier0", "Low" },
            { "set.tier1", "Medium" },
            { "set.tier2", "High" },
            { "set.tier3", "Ultra" },
            { "set.vsync_on", "VSync on" },
            { "set.vsync_off", "VSync off" },
            { "set.frame", "Frame cap:" },
            { "set.resolution", "Resolution:" },
            { "set.aim_off", "Aim assist off" },
            { "set.aim_light", "Aim assist light" },
            { "set.aim_strong", "Aim assist strong" },
            { "set.invert", "Invert look" },
            { "set.look", "Look: normal" },
            { "set.crouch_toggle", "Crouch: toggle" },
            { "set.crouch_hold", "Crouch: hold" },
            { "set.sprint_toggle", "Sprint: toggle" },
            { "set.sprint_hold", "Sprint: hold" },
            { "set.merciful", "Death: merciful" },
            { "set.perma", "Death: permadeath" },
            { "set.next", "Next run:" },
            { "set.gore", "Gore:" },
            { "set.hit_on", "Hit stop on" },
            { "set.hit_off", "Hit stop off" },
            { "set.num_on", "Damage numbers on" },
            { "set.num_off", "Damage numbers off" },
            { "set.blur_on", "Motion blur on" },
            { "set.blur_off", "Motion blur off" },
            { "set.window", "Windowed" },
            { "set.full", "Fullscreen" },
            { "set.display", "Display: default" },
            { "set.keys", "Click an action, then press a key. Escape cancels." },
            { "set.reset_keys", "Reset keys" },
            { "set.pad", "Click a pad action, then press a button. Escape cancels." },
            { "set.reset_pad", "Reset pad" },
            { "set.revert", "Revert" },
            { "set.close", "Close" }
        };

        private static readonly Dictionary<string, string> spanish = new Dictionary<string, string>
        {
            { "hud.expedition", "PUESTO CERO — EXPEDICIÓN" },
            { "hud.health", "Salud" },
            { "hud.stamina", "Aguante" },
            { "hud.extract", "Llega a la puerta del santuario para extraer" },
            { "menu.pause", "PAUSA" },
            { "menu.resume", "Continuar" },
            { "menu.save", "Guardar" },
            { "menu.camp", "Santuario" },
            { "menu.settings", "Ajustes" },
            { "menu.main", "Menú principal" },
            { "menu.codex", "Códice" },
            { "menu.skip", "Saltar la lección" },
            { "menu.restart", "Reiniciar" },
            { "menu.leader", "LÍDER CAÍDO" },
            { "menu.choose", "Elige quién sale al amanecer." },
            { "menu.falls", "El puesto cae" },
            { "menu.holds", "EL PUESTO RESISTE" },
            { "menu.broadcast", "La emisión salió. La puerta puede quedar cerrada." },
            { "menu.enter", "Entrar al santuario" },
            { "menu.endless", "Seguir las noches" },
            { "menu.new", "Nuevo puesto" },
            { "menu.air", "La torre está al aire." },
            { "menu.supplies", "Los suministros volvieron a la puerta." },
            { "menu.next", "Siguiente:" },
            { "menu.names", "nombres en el muro." },
            { "menu.names_none", "Todos los nombres del registro se han ido." },
            { "menu.credits", "CRÉDITOS" },
            { "menu.brand", "Puesto Cero" },
            { "menu.blurb", "Un santuario, una calle, y quien siga en el tablero." },
            { "menu.back", "Volver" },
            { "menu.title", "PUESTO CERO" },
            { "menu.version", "Versión" },
            { "menu.continue", "Continuar partida" },
            { "menu.saves", "Partidas" },
            { "menu.street", "Volver a la calle" },
            { "menu.board", "Tablero local" },
            { "menu.board_empty", "Aún no hay partidas terminadas." },
            { "camp.title", "SANTUARIO" },
            { "result.title", "EXPEDICIÓN COMPLETA" },
            { "gameover.title", "EL PUESTO CAE" },
            { "diff.scavenger", "Carroñero" },
            { "diff.survivor", "Superviviente" },
            { "diff.nightmare", "Pesadilla" },
            { "set.title", "AJUSTES" },
            { "set.shake", "Sacudida" },
            { "set.volume", "Volumen" },
            { "set.effects", "Efectos" },
            { "set.music", "Música" },
            { "set.ambience", "Ambiente" },
            { "set.ui", "Interfaz" },
            { "set.fov", "Campo visual" },
            { "set.text", "Texto" },
            { "set.hud", "HUD" },
            { "set.bright", "Brillo" },
            { "set.subs_on", "Subtítulos sí" },
            { "set.subs_off", "Subtítulos no" },
            { "set.color", "Modo daltónico" },
            { "set.quality", "Calidad:" },
            { "set.tier0", "Baja" },
            { "set.tier1", "Media" },
            { "set.tier2", "Alta" },
            { "set.tier3", "Ultra" },
            { "set.vsync_on", "Sincronía sí" },
            { "set.vsync_off", "Sincronía no" },
            { "set.frame", "Límite:" },
            { "set.resolution", "Resolución:" },
            { "set.aim_off", "Asistencia no" },
            { "set.aim_light", "Asistencia leve" },
            { "set.aim_strong", "Asistencia fuerte" },
            { "set.invert", "Mirar invertido" },
            { "set.look", "Mirar normal" },
            { "set.crouch_toggle", "Agacharse: alternar" },
            { "set.crouch_hold", "Agacharse: mantener" },
            { "set.sprint_toggle", "Correr: alternar" },
            { "set.sprint_hold", "Correr: mantener" },
            { "set.merciful", "Muerte clemente" },
            { "set.perma", "Muerte permanente" },
            { "set.next", "Siguiente:" },
            { "set.gore", "Gore:" },
            { "set.hit_on", "Impacto sí" },
            { "set.hit_off", "Impacto no" },
            { "set.num_on", "Números sí" },
            { "set.num_off", "Números no" },
            { "set.blur_on", "Desenfoque sí" },
            { "set.blur_off", "Desenfoque no" },
            { "set.window", "Ventana" },
            { "set.full", "Pantalla completa" },
            { "set.display", "Pantalla predeterminada" },
            { "set.keys", "Pulsa una acción y luego una tecla. Escape cancela." },
            { "set.reset_keys", "Restablecer teclas" },
            { "set.pad", "Pulsa una acción del mando y luego un botón. Escape cancela." },
            { "set.reset_pad", "Restablecer mando" },
            { "set.revert", "Revertir" },
            { "set.close", "Cerrar" }
        };

        public static string T(string key)
        {
            string language = SettingsService.Instance != null ? SettingsService.Instance.Language : "en";
            return T(key, language);
        }

        public static string T(string key, string language)
        {
            var table = language == "es" ? spanish : english;
            return table.TryGetValue(key, out var value) ? value : key;
        }

        public static string Difficulty(int stored)
        {
            int level = stored <= 0 ? 2 : stored >= 3 ? 3 : stored;
            if (level == 1) return T("diff.scavenger");
            if (level == 3) return T("diff.nightmare");
            return T("diff.survivor");
        }
    }
}
