using System.Collections.Generic;
using OutpostZero.Core;

namespace OutpostZero.Shell
{
    public static class Loc
    {
        private static readonly Dictionary<string, string> english = new Dictionary<string, string>
        {
            { "hud.expedition", "OUTPOST ZERO — EXPEDITION" },
            { "hud.health", "Health" },
            { "hud.stamina", "Stamina" },
            { "hud.lamp", "Lamp" },
            { "hud.extract", "Reach the sanctuary gate to extract" },
            { "hud.hunger", "Hunger" },
            { "hud.thirst", "Thirst" },
            { "hud.fatigue", "Fatigue" },
            { "hud.hungry", "Hungry" },
            { "hud.thirsty", "Thirsty" },
            { "hud.exhausted", "Exhausted" },
            { "hud.exposure", "Exposure" },
            { "hud.bleeding", "Bleeding" },
            { "hud.poison", "Poison" },
            { "hud.adrenaline", "Adrenaline" },
            { "hud.burn", "On fire" },
            { "burn.you", "You're on fire" },
            { "hud.infect1", "Infection I" },
            { "hud.infect2", "Infection II" },
            { "hud.infect3", "Infection III" },
            { "hud.watch", "Watchtower" },
            { "hud.kills", "Kills" },
            { "hud.scrap", "Scrap" },
            { "hud.tension", "Tension" },
            { "hud.state.calm", "Calm" },
            { "hud.state.build", "BuildUp" },
            { "hud.state.peak", "Peak" },
            { "hud.state.relax", "Relax" },
            { "hud.hold", "Hold to extract" },
            { "hud.hit.front", "Hit from the front" },
            { "hud.hit.back", "Hit from behind" },
            { "hud.hit.left", "Hit from the left" },
            { "hud.hit.right", "Hit from the right" },
            { "hud.noweapon", "No weapon" },
            { "hud.reload", "reload" },
            { "hud.low", "low" },
            { "hud.raid", "Raid" },
            { "menu.pause", "PAUSED" },
            { "menu.resume", "Resume" },
            { "menu.save", "Save" },
            { "menu.camp", "Sanctuary" },
            { "menu.settings", "Settings" },
            { "menu.main", "Main Menu" },
            { "menu.codex", "Codex" },
            { "menu.skip", "Skip the lesson" },
            { "menu.restart", "Restart" },
            { "menu.leader", "LEADER KILLED" },
            { "menu.choose", "Choose who walks out at dawn." },
            { "menu.falls", "The outpost falls" },
            { "menu.holds", "OUTPOST HOLDS" },
            { "menu.broadcast", "The broadcast went out. The gate can stay shut." },
            { "menu.enter", "Enter sanctuary" },
            { "menu.endless", "Keep the nights" },
            { "menu.new", "New outpost" },
            { "menu.air", "The tower is on the air." },
            { "menu.supplies", "Supplies are back inside the gate." },
            { "menu.next", "Next:" },
            { "menu.names", "names on the memorial wall." },
            { "menu.names_none", "Every name on the roster is gone." },
            { "menu.credits", "CREDITS" },
            { "menu.brand", "Outpost Zero" },
            { "menu.blurb", "A sanctuary, a street, and whoever is still on the board." },
            { "menu.tones", "Every tone is generated in the game." },
            { "menu.tones_n", "generated tones" },
            { "menu.back", "Back" },
            { "menu.title", "OUTPOST ZERO" },
            { "menu.version", "Version" },
            { "menu.continue", "Continue" },
            { "menu.saves", "Saves" },
            { "slot.title", "SAVES" },
            { "slot.word", "Slot" },
            { "slot.day", "day" },
            { "slot.empty", "empty" },
            { "slot.auto", "Autosave" },
            { "menu.street", "Back to the street" },
            { "menu.board", "Local board" },
            { "menu.board_empty", "No finished runs yet." },
            { "camp.title", "SANCTUARY" },
            { "result.title", "EXPEDITION COMPLETE" },
            { "result.kills", "kills" },
            { "result.scrap", "scrap" },
            { "result.street", "Street" },
            { "note.grief", "A death in the camp" },
            { "note.recovery", "Someone is on their feet" },
            { "note.fever", "A fever spread" },
            { "note.stew", "The pot cooked" },
            { "note.soak", "The yard is soaked" },
            { "note.friendship", "A friendship formed" },
            { "note.argument", "An argument at the table" },
            { "note.breakdown", "Someone broke" },
            { "note.celebration", "The camp celebrated" },
            { "gameover.title", "THE OUTPOST FALLS" },
            { "diff.scavenger", "Scavenger" },
            { "diff.survivor", "Survivor" },
            { "diff.nightmare", "Nightmare" },
            { "set.title", "SETTINGS" },
            { "set.shake", "Shake" },
            { "set.volume", "Volume" },
            { "set.effects", "Effects" },
            { "set.music", "Music" },
            { "set.ambience", "Ambience" },
            { "set.ui", "Interface" },
            { "set.fov", "Field of view" },
            { "set.text", "Text" },
            { "set.hud", "HUD" },
            { "set.bright", "Brightness" },
            { "set.subs_on", "Subtitles on" },
            { "set.subs_off", "Subtitles off" },
            { "set.flash_on", "Flashes on" },
            { "set.flash_off", "Flashes off" },
            { "set.color", "Colorblind mode" },
            { "set.vision0", "Off" },
            { "set.vision1", "Blue-yellow" },
            { "set.vision2", "Mono" },
            { "set.quality", "Quality:" },
            { "set.tier0", "Low" },
            { "set.tier1", "Medium" },
            { "set.tier2", "High" },
            { "set.tier3", "Ultra" },
            { "set.vsync_on", "VSync on" },
            { "set.vsync_off", "VSync off" },
            { "set.frame", "Frame cap:" },
            { "set.resolution", "Resolution:" },
            { "set.aim_off", "Aim assist off" },
            { "set.aim_light", "Aim assist light" },
            { "set.aim_strong", "Aim assist strong" },
            { "set.invert", "Invert look" },
            { "set.look", "Look: normal" },
            { "set.crouch_toggle", "Crouch: toggle" },
            { "set.crouch_hold", "Crouch: hold" },
            { "set.sprint_toggle", "Sprint: toggle" },
            { "set.sprint_hold", "Sprint: hold" },
            { "set.merciful", "Death: merciful" },
            { "set.perma", "Death: permadeath" },
            { "set.next", "Next run:" },
            { "set.gore", "Gore:" },
            { "set.hit_on", "Hit stop on" },
            { "set.hit_off", "Hit stop off" },
            { "set.num_on", "Damage numbers on" },
            { "set.num_off", "Damage numbers off" },
            { "set.blur_on", "Motion blur on" },
            { "set.blur_off", "Motion blur off" },
            { "set.window", "Windowed" },
            { "set.full", "Fullscreen" },
            { "set.display", "Display: default" },
            { "set.keys", "Click an action, then press a key. Escape cancels." },
            { "bind.press", "Press a key for" },
            { "bind.button", "Press a button for" },
            { "bind.pad", "Pad" },
            { "bind.Pause", "Pause" },
            { "bind.Reload", "Reload" },
            { "bind.Interact", "Interact" },
            { "bind.Medkit", "Medkit" },
            { "bind.Flashlight", "Flashlight" },
            { "bind.Crouch", "Crouch" },
            { "bind.Sprint", "Sprint" },
            { "bind.Inventory", "Inventory" },
            { "bind.Throw", "Throw" },
            { "bind.Takedown", "Takedown" },
            { "bind.Build", "Build" },
            { "bind.Wheel", "Wheel" },
            { "bind.Fire", "Fire" },
            { "bind.Aim", "Aim" },
            { "bind.NextWeapon", "NextWeapon" },
            { "bind.PrevWeapon", "PrevWeapon" },
            { "bind.Dodge", "Dodge" },
            { "set.reset_keys", "Reset keys" },
            { "set.pad", "Click a pad action, then press a button. Escape cancels." },
            { "set.reset_pad", "Reset pad" },
            { "set.revert", "Revert" },
            { "set.close", "Close" },
            { "task.rest", "Rest" },
            { "task.scavenge", "Scavenge" },
            { "task.guard", "Guard" },
            { "task.cook", "Cook" },
            { "task.medic", "Medic" },
            { "task.build", "Build" },
            { "task.clear", "Clear" },
            { "task.lead", "Lead" },
            { "task.fallen", "Fallen" },
            { "task.quarantine", "Quarantine" },
            { "camp.scrap", "Scrap" },
            { "camp.food", "Food" },
            { "camp.water", "Water" },
            { "camp.cloth", "Cloth" },
            { "camp.chem", "Chem" },
            { "camp.tape", "Tape" },
            { "camp.raw", "Raw" },
            { "camp.wear", "Wear" },
            { "camp.tired", "Worn out" },
            { "camp.rounds", "Rounds" },
            { "camp.cell", "Lamp cells" },
            { "camp.press", "Pressed" },
            { "camp.fuel", "Fuel" },
            { "camp.shots", "Shots" },
            { "camp.bodies", "Bodies" },
            { "camp.lamps", "The lights catch them" },
            { "camp.warn", "The tower sees them" },
            { "camp.dusk", "Dusk brings them" },
            { "camp.hit", "is hit" },
            { "camp.fell", "fell" },
            { "camp.wiped", "The camp is gone" },
            { "camp.spoiled", "The stores spilled" },
            { "camp.brute", "A brute is at the boards" },
            { "camp.chew", "They chew the boards" },
            { "camp.line", "The guards hold the line" },
            { "camp.sides", "sides" },
            { "camp.dark", "The yard goes dark" },
            { "raid.tower", "Broadcast night — hold the tower" },
            { "raid.from", "Night raid from the" },
            { "raid.gate", "gate" },
            { "raid.alley", "alley" },
            { "raid.yard", "yard" },
            { "raid.fence", "fence" },
            { "raid.broadcast", "The broadcast went out" },
            { "raid.held", "The gate held" },
            { "raid.broke", "The raid broke the stores" },
            { "raid.coming", "They come from the" },
            { "camp.haul", "Haul the yard" },
            { "camp.mend", "Mend the boards" },
            { "camp.morning", "Haul the yard and mend the boards" },
            { "camp.quiet", "The dead fall back" },
            { "camp.slept", "You sleep" },
            { "camp.cot_sleep", "The cot holds the night" },
            { "camp.gen_on", "Generator on" },
            { "camp.gen_off", "Generator dark" },
            { "camp.morale", "Morale" },
            { "camp.memorial", "Memorial wall" },
            { "camp.caravan", "Caravan" },
            { "camp.away", "away" },
            { "camp.at_gate", "at the gate" },
            { "camp.advance", "Advance watch" },
            { "camp.raid_yes", "A raid is likely tonight." },
            { "camp.raid_no", "The street is quiet tonight." },
            { "camp.endure", "Endure the night" },
            { "camp.build", "Build [B] then click." },
            { "camp.barricade", "Barricade" },
            { "camp.cot", "Cot" },
            { "camp.tower", "Tower" },
            { "camp.generator", "Generator" },
            { "camp.bench", "Bench" },
            { "camp.farm", "Farm" },
            { "camp.purifier", "Purifier" },
            { "camp.turret", "Turret" },
            { "camp.turret_tier", "The turret wants a tier-2 bench" },
            { "camp.spikes", "Spikes" },
            { "camp.oil", "Oil" },
            { "camp.raising", "Raising" },
            { "camp.mend", "Mend" },
            { "camp.crate", "Crate" },
            { "camp.lamp", "Floodlight" },
            { "camp.fire", "Campfire" },
            { "camp.room", "Stores" },
            { "camp.sprout", "Farm sprouts" },
            { "camp.post", "Post" },
            { "camp.craft", "Craft" },
            { "camp.bench_raise", "Raise the bench" },
            { "camp.bench_t2", "Bench T2" },
            { "camp.plans", "Plans" },
            { "camp.print", "Blueprint" },
            { "camp.radio_full", "The tower has its parts" },
            { "gate.tier", "Need a tier-2 bench" },
            { "gate.print", "Need that blueprint" },
            { "gate.gen", "Need a damaged generator" },
            { "gate.bench", "Need a workbench" },
            { "gate.cot", "Need a medical cot" },
            { "gate.station", "Need a station" },
            { "gate.medic", "Need a medic on duty" },
            { "stall.bench", "Use workbench" },
            { "stall.fire", "Cook and rest" },
            { "stall.cot", "Treat wounds" },
            { "stall.water", "Draw water" },
            { "stall.gen", "Fuel the generator" },
            { "stall.trade", "Trade" },
            { "stall.open", "Workbench open — craft from the camp menu" },
            { "stall.wounds", "Wounds treated" },
            { "stall.drawn", "Water collected" },
            { "stall.fueled", "Generator fueled" },
            { "stall.scrap", "Need 4 camp scrap" },
            { "stall.short", "Not enough camp supplies" },
            { "stall.buy", "Buy" },
            { "stall.sell", "Sell bandage" },
            { "stall.deliver", "Deliver 4 medkits" },
            { "stall.leave", "Leave" },
            { "stall.refuse", "will not trade" },
            { "stall.caravan", "The Caravan" },
            { "stall.militia", "Iron Militia" },
            { "stall.clinic", "The Clinic" },
            { "stall.farmers", "Free Farmers" },
            { "quest.clinic", "The Clinic wants 4 medkits" },
            { "quest.clinic_done", "Field dressings learned" },
            { "quest.farmers", "Clear a district for the farmers" },
            { "quest.farmers_done", "Farmers remember the nest" },
            { "quest.militia", "Iron Militia sells rifle and shell ammo" },
            { "quest.caravan", "Extract on a visit day and the caravan pays" },
            { "quest.caravan_done", "Escort complete" },
            { "gate.wall", "Need a damaged barricade" },
            { "print.dressing", "Field dressings" },
            { "print.flare", "Flare" },
            { "print.repair", "Generator repair" },
            { "print.wall", "Reinforced wall" },
            { "print.radio", "Radio spare" },
            { "camp.radio", "Radio" },
            { "camp.reroll", "Reroll street" },
            { "camp.broadcast_holds", "The broadcast holds. The nights keep coming." },
            { "camp.tower_air", "The tower is on the air." },
            { "camp.broadcast", "Broadcast night" },
            { "camp.tower_needs", "The tower needs three radio parts and a built generator." },
            { "camp.district", "District" },
            { "camp.clear", "clear" },
            { "camp.part", "part" },
            { "camp.closed", "road closed" },
            { "camp.fog", "Unmapped roads" },
            { "camp.trip", "Fuel burned" },
            { "camp.searched", "searched" },
            { "poi.cache", "Supply cache" },
            { "poi.radio", "Radio part" },
            { "sky.clear", "Clear" },
            { "sky.fog", "Fog" },
            { "sky.rain", "Rain" },
            { "sky.overcast", "Overcast" },
            { "sky.storm", "Storm" },
            { "camp.leave", "Leave for the district" },
            { "camp.pack", "PACK" },
            { "camp.weight", "Weight" },
            { "camp.pack_raise", "Field pack" },
            { "camp.pack_t2", "The pack holds 50" },
            { "camp.use", "Use" },
            { "camp.info", "Info" },
            { "camp.belt", "Belt" },
            { "camp.drop", "Drop" },
            { "camp.split", "Split" },
            { "camp.container", "Container" },
            { "camp.take_all", "Take all" },
            { "camp.take", "Take" },
            { "camp.unknown", "Unknown" },
            { "camp.unseen", "Not seen yet." },
            { "camp.seed", "seed" },
            { "camp.opinion", "opinion" },
            { "camp.close", "close" },
            { "camp.gift", "Gift meal" },
            { "camp.strip", "Strip gun" },
            { "camp.strip_none", "Keep one weapon" },
            { "camp.strip_full", "Stores are full" },
            { "camp.strip_ok", "Parts recovered" },
            { "camp.gift_none", "No meal to give" },
            { "camp.gift_ok", "Meal shared" },
            { "bond.partner", "Partner" },
            { "bond.friend", "Friend" },
            { "bond.rival", "Rival" },
            { "camp.leads", "Leads" },
            { "camp.codex", "Codex:" },
            { "camp.heavy", "Pack is too heavy" },
            { "camp.picked", "Picked up" },
            { "unit.health", "health" },
            { "unit.hunger", "hunger" },
            { "unit.thirst", "thirst" },
            { "unit.rounds", "rounds" },
            { "unit.cure", "Clears infection" },
            { "unit.relief", "+20 health over 20s" },
            { "unit.lure", "Draws the dead" },
            { "unit.molotov", "Fire on impact" },
            { "unit.flare", "Pulls a search for 20s" },
            { "unit.cell", "Fills the lamp by 60" },
            { "lamp.full", "The lamp is full" },
            { "lamp.fit", "Lamp cell fitted" },
            { "toss.none", "Nothing to throw" },
            { "toss.take_bottle", "Take the bottle" },
            { "unit.pipe_bomb", "Blast on impact" },
            { "unit.cloth", "Bandages and fire bottles" },
            { "unit.chemicals", "Ammo and medicine" },
            { "unit.tape", "Holds a medkit together" },
            { "unit.material", "Camp scrap" },
            { "item.medkit", "Medkit" },
            { "item.bandage", "Bandage" },
            { "item.antibiotics", "Antibiotics" },
            { "item.painkillers", "Painkillers" },
            { "item.canned_food", "Canned Food" },
            { "item.raw_food", "Raw Food" },
            { "item.print_flare", "Flare Blueprint" },
            { "item.print_repair", "Repair Blueprint" },
            { "item.print_wall", "Wall Blueprint" },
            { "item.print_radio", "Radio Blueprint" },
            { "item.water", "Water Bottle" },
            { "item.ammo_9mm", "9mm Rounds" },
            { "item.ammo_shells", "Shotgun Shells" },
            { "item.ammo_rifle", "Rifle Magazine" },
            { "item.ammo_smg", "SMG Magazine" },
            { "item.scrap", "Scrap" },
            { "item.cloth", "Cloth" },
            { "item.chemicals", "Chemicals" },
            { "item.tape", "Duct Tape" },
            { "item.noise_lure", "Noise Lure" },
            { "item.molotov", "Molotov" },
            { "item.flare", "Flare" },
            { "item.cell", "Lamp cell" },
            { "item.pipe_bomb", "Pipe Bomb" },
            { "item.street_bottle", "Street Bottle" },
            { "blurb.medkit", "Stops bleeding and breaks a fever." },
            { "blurb.bandage", "Stops bleeding." },
            { "blurb.antibiotics", "Works before the fever turns lethal." },
            { "blurb.painkillers", "A slow mend, not a cure." },
            { "blurb.canned_food", "Heavy, and it keeps." },
            { "blurb.raw_food", "Thin if you eat it. A campfire makes a meal." },
            { "blurb.water", "One bottle covers about ten minutes." },
            { "blurb.ammo_9mm", "Fits the pistol." },
            { "blurb.ammo_shells", "Fits the shotgun." },
            { "blurb.ammo_rifle", "Fits the rifle." },
            { "blurb.ammo_smg", "Fits the compact SMG." },
            { "blurb.scrap", "The camp spends this." },
            { "blurb.cloth", "Turns into bandages at the sanctuary." },
            { "blurb.chemicals", "The bench needs a measure for each batch of rounds." },
            { "blurb.tape", "One roll finishes a medkit." },
            { "blurb.noise_lure", "Throw it to pull a horde off a door." },
            { "blurb.molotov", "Breaks into fire." },
            { "blurb.flare", "Burns for twenty seconds and pulls a search." },
            { "blurb.pipe_bomb", "A short, hard explosion." },
            { "blurb.street_bottle", "Breaks loud enough to pull a group." },
            { "dist.ash_market", "Ash Market" },
            { "dist.rail_yard", "Rail Yard" },
            { "dist.old_hospital", "Old Hospital" },
            { "dist.north_gate", "North Gate" },
            { "dist.commercial_strip", "Commercial Strip" },
            { "dist.police_station", "Police Station" },
            { "dist.water_plant", "Water Plant" },
            { "dist.mall", "Mall" },
            { "dist.highway_overpass", "Highway Overpass" },
            { "dist.downtown_core", "Downtown Core" },
            { "trait.steady", "Steady Hands" },
            { "trait.sleeper", "Light Sleeper" },
            { "trait.medic", "Field Medic" },
            { "trait.scrounger", "Scrounger" },
            { "trait.watchful", "Watchful" },
            { "trait.volatile", "Volatile" },
            { "trait.glutton", "Glutton" },
            { "trait.engineer", "Engineer" },
            { "trait.cook", "Cook" },
            { "trait.sharp", "Sharpshooter" },
            { "trait.brave", "Brave" },
            { "trait.coward", "Cowardly" },
            { "trait.insomniac", "Insomniac" },
            { "trait.optimist", "Optimist" },
            { "trait.loner", "Loner" },
            { "trait.owl", "Night Owl" },
            { "barrel.hiss", "The barrel is hissing" },
            { "ambush.warn", "The militia has the dead waiting" },
            { "past.nurse", "Nurse" },
            { "past.driver", "Driver" },
            { "past.teacher", "Teacher" },
            { "past.mechanic", "Mechanic" },
            { "past.clerk", "Clerk" },
            { "past.soldier", "Soldier" },
            { "mood.inspired", "Inspired" },
            { "mood.steady", "Steady" },
            { "mood.depressed", "Depressed" },
            { "mood.breakdown", "Breakdown" },
            { "bill.craft", "Craft" },
            { "bill.scrap", "scrap" },
            { "bill.cloth", "cloth" },
            { "bill.chem", "chem" },
            { "bill.tape", "tape" },
            { "clock.day", "Day" },
            { "clock.morning", "morning watch" },
            { "dose.kit", "Medkit used" },
            { "dose.hp", "HP" },
            { "dose.fail", "Antibiotics won't help" },
            { "dose.break", "The fever breaks" },
            { "dose.spent", "Used" },
            { "pack.fullbelt", "Belt is full" },
            { "pack.clear", "Cleared belt" },
            { "pack.belt", "Belt" },
            { "pack.dropped", "Dropped" },
            { "pack.pack", "Pack is full" },
            { "pack.poison", "Poisoned" },
            { "pack.made", "Crafted" },
            { "loot.left", "Left some loot behind" },
            { "loot.open", "Container open" },
            { "loot.empty", "Empty" },
            { "gate.open", "Pick an open district" },
            { "gate.drag", "Dragged back to the gate" },
            { "gate.quota", "Objectives unfinished" },
            { "gate.close", "They're too close" },
            { "gate.road", "That road is still closed" },
            { "gate.radio", "Radio part recovered" },
            { "gate.out", "The broadcast is already out" },
            { "gate.extracted", "Extracted" },
            { "save.fail", "Save failed" },
            { "save.ok", "Game saved" },
            { "save.none", "No save file" },
            { "save.bad", "Save could not be read" },
            { "save.loaded", "Save loaded" },
            { "save.auto", "Autosave loaded" },
            { "yard.mode", "Build mode: click the yard" },
            { "yard.off", "Build mode off" },
            { "yard.facing", "Facing" },
            { "yard.recovered", "Recovered" },
            { "yard.scrap", "scrap" },
            { "yard.taken", "That square is taken" },
            { "yard.need", "Need" },
            { "yard.needtail", "camp scrap" },
            { "yard.marked", "Site marked" },
            { "yard.up", "is up" },
            { "yard.patched", "Patched" },
            { "yard.mended", "Mended" },
            { "yard.gave", "A barricade gave way" },
            { "yard.spikes", "The spikes broke" },
            { "yard.oil", "The oil catches" },
            { "yard.kind.barricade", "Barricade" },
            { "yard.kind.cot", "Cot" },
            { "yard.kind.water", "Water" },
            { "yard.kind.watchtower", "Watchtower" },
            { "yard.kind.generator", "Generator" },
            { "yard.kind.workbench", "Workbench" },
            { "yard.kind.tradingpost", "TradingPost" },
            { "yard.kind.farm", "Farm" },
            { "yard.kind.purifier", "Purifier" },
            { "yard.kind.turret", "Turret" },
            { "yard.kind.spikes", "Spikes" },
            { "yard.kind.oil", "Oil" },
            { "yard.kind.crate", "Crate" },
            { "yard.kind.lamp", "Lamp" },
            { "yard.kind.campfire", "Campfire" },
            { "fight.start", "Takedown" },
            { "fight.slip", "Takedown slipped" },
            { "fight.down", "Down" },
            { "fight.burst", "Pipe bomb burst" },
            { "fight.flare", "Flare lit" },
            { "fight.molotov", "Molotov burst" },
            { "fight.lure", "Lure clattered" },
            { "fight.barrel", "Barrel exploded" },
            { "fight.toxic", "Toxic cloud" },
            { "fight.oil", "Oil spill" },
            { "pane.break", "The pane shatters" },
            { "pane.cut", "Glass cuts" },
            { "ash.air", "Ash hangs in the air" },
            { "home.bite", "The bite came home" },
            { "home.fever", "The fever came home" },
            { "hurt.bite", "Bitten" },
            { "hurt.fever", "Fever" },
            { "hurt.critical", "Critical" },
            { "cot.bed", "On the cot" },
            { "cot.well", "They are not hurt" },
            { "limp.bite", "The bite slows you" },
            { "limp.fever", "The fever slows you" },
            { "limp.critical", "You can barely walk" },
            { "ease.wound", "The wound eases" },
            { "ease.follow", "Ease the bite" },
            { "rain.catch", "The collector caught the rain" },
            { "rain.storm", "The collector caught the storm" },
            { "tank.storm", "A storm drinks the tank" },
            { "yard.storm", "The storm wore the yard" },
            { "yard.rain", "The rain wore the yard" },
            { "swing.tired", "Too tired to swing" },
            { "door.bar", "Barred" },
            { "door.hold", "The bar holds" },
            { "door.gives", "The bar gives" },
            { "door.rattle", "The bar rattles" },
            { "door.shot", "The shot hits the bar" },
            { "rack.wound", "The wound slows your hands" },
            { "post.bite", "The bite pulls the shot" },
            { "fight.held", "Already carrying that" },
            { "fight.took", "Took" },
            { "fight.swap", "Swapped weapons" },
            { "fight.boards", "The boards gave way" },
            { "fight.roster", "The roster is full" },
            { "fight.tower", "The tower is not ready" },
            { "fight.ledger", "The board could not be written" },
            { "fight.gun.pistol_9mm", "Tactical 9mm Pistol" },
            { "fight.gun.shotgun_pump", "Remington 870 Shotgun" },
            { "fight.gun.rifle_assault", "Assault Rifle" },
            { "fight.gun.smg", "Compact SMG" },
            { "fight.gun.machete", "Steel Machete" },
            { "stall.wait", "No caravan until the next visit" },
            { "stall.shake", "The merchant shakes their head" },
            { "stall.pack", "The pack is full" },
            { "stall.nobandage", "No bandage to barter" },
            { "stall.bartered", "Bartered a bandage for" },
            { "stall.barterscrap", "scrap" },
            { "stall.blueprint", "Clinic blueprint: field dressings" },
            { "stall.nest", "Free Farmers remember the cleared nest" },
            { "stall.through", "The Caravan made it through" },
            { "stall.sealed", "deal sealed" },
            { "stall.gate", "is at the gate" },
            { "ask.search", "Search container" },
            { "ask.take", "Take from container" },
            { "ask.radio", "Take the radio part" },
            { "ask.cache", "Search the cache" },
            { "ask.gear", "Recover gear" },
            { "ask.back", "Back inside the gate" },
            { "ask.along", "Bring" },
            { "ask.along2", "along" },
            { "ask.togate", "Bring" },
            { "ask.togate2", "to the gate" },
            { "ask.with", "is with you" },
            { "ask.takes", "takes the gate" },
            { "ask.survivor", "Survivor" },
            { "ask.in", "Step inside" },
            { "ask.out", "Step outside" },
            { "ask.findcache", "Find the cache" },
            { "ask.findradio", "Find the radio part" },
            { "ask.searched", "Cache searched" },
            { "ask.stowed", "Radio part stowed" },
            { "ask.stays", "stays at the sanctuary" },
            { "ask.cry", "cries out" },
            { "ask.swing", "swings" },
            { "ask.bitten", "is bitten" },
            { "ask.drag", "can barely keep up" },
            { "ask.falls", "falls" },
            { "ask.kept", "Gear recovered" },
            { "ask.nameonly", "Nothing left but the name" },
            { "door.inside", "Inside" },
            { "door.street", "Back on the street" },
            { "craft.fitted", "fitted" },
            { "ask.brief.ash_market", "Loot the stalls, watch the alleys" },
            { "ask.brief.rail_yard", "Barrels and a brute pack" },
            { "ask.brief.old_hospital", "Medical caches, infected wards" },
            { "ask.brief.north_gate", "The ring road north of the plant" },
            { "ask.brief.commercial_strip", "Shops still have cans in the back" },
            { "ask.brief.police_station", "The armoury is on the second floor" },
            { "ask.brief.water_plant", "Tanks, catwalks, and a long fence" },
            { "ask.brief.mall", "The atrium is dark and full of echoes" },
            { "ask.brief.highway_overpass", "Cars stacked under the span" },
            { "ask.brief.downtown_core", "The tower site is past the plaza" },
            { "load.boot", "WAKING THE GATE" },
            { "load.sanctuary", "THE SANCTUARY" },
            { "load.expedition", "INTO THE DISTRICT" },
            { "load.results", "BACK INSIDE" },
            { "load.brand", "OUTPOST ZERO" },
            { "load.tip0", "Noise carries farther than the shot that made it." },
            { "load.tip1", "Crouch before you fire. The street hears you stand." },
            { "load.tip2", "A dark block still has eyes past the lamplight." },
            { "load.tip3", "Extract at the sanctuary gate. The bag does not walk home." },
            { "load.tip4", "Barricades fail when nobody is posted on Guard." },
            { "load.tip5", "Cooked food lifts morale. A skipped meal does not." },
            { "load.tip6", "The generator drinks fuel once dusk settles." },
            { "load.tip7", "Three radio parts and a built generator open broadcast night." },
            { "load.tip8", "Reload before the magazine clicks empty." },
            { "load.tip9", "Oil, toxic, and powder barrels chain if you break them." },
            { "load.tip10", "A medic on the board closes wounds between watches." },
            { "load.tip11", "Save before you leave the gate." },
            { "tape.walker", "Walker" },
            { "tape.runner", "Runner" },
            { "tape.brute", "Brute" },
            { "head.gate", "Gate" },
            { "head.poi", "POI" },
            { "head.behind", "behind" },
            { "head.front", "front" },
            { "head.back", "back" },
            { "head.left", "left" },
            { "head.right", "right" },
            { "wheel.empty", "empty" },
            { "board.held", "Held" },
            { "board.fell", "Fell" },
            { "board.day", "day" },
            { "board.kills", "kills" },
            { "board.lost", "lost" },
            { "board.streets", "streets" },
            { "frame.auto", "Auto" },
            { "frame.30", "30 fps" },
            { "frame.60", "60 fps" },
            { "frame.120", "120 fps" },
            { "frame.uncapped", "Uncapped" },
            { "watch.title", "watch" },
            { "watch.player", "Player" },
            { "watch.vfx", "vfx" },
            { "watch.peak", "peak" },
            { "watch.state.idle", "Idle" },
            { "watch.state.wander", "Wander" },
            { "watch.state.investigatenoise", "InvestigateNoise" },
            { "watch.state.searching", "Searching" },
            { "watch.state.chase", "Chase" },
            { "watch.state.attack", "Attack" },
            { "watch.state.dead", "Dead" },
            { "bark.cant", "I can't do this." },
            { "bark.cook", "Fire's lit." },
            { "bark.guard", "Watching the gate." },
            { "bark.medic", "Hold still." },
            { "bark.scavenge", "I'll check the piles." },
            { "bark.build", "I'll raise it." },
            { "bark.clear", "I'll haul them." },
            { "bark.hold", "We'll hold." },
            { "bark.rest", "Resting." },
            { "bark.visit", "Good to see you." },
            { "task.visit", "Visit" },
            { "bark.tired", "My legs are done." },
            { "recipe.bandage", "Bandage" },
            { "recipe.medkit", "Medkit" },
            { "recipe.antibiotics", "Antibiotics" },
            { "recipe.painkillers", "Painkillers" },
            { "recipe.ammo_9mm", "9mm (12)" },
            { "recipe.ammo_shells", "Shells (6)" },
            { "recipe.ammo_rifle", "Rifle mag" },
            { "recipe.ammo_smg", "SMG mag" },
            { "recipe.noise_lure", "Noise lure" },
            { "recipe.molotov", "Molotov" },
            { "recipe.pipe_bomb", "Pipe Bomb" },
            { "recipe.suppressor", "Suppressor" },
            { "recipe.rail", "Flashlight rail" },
            { "recipe.optic", "Optic" },
            { "recipe.extended_mag", "Extended mag" },
            { "recipe.dressing", "Field dressings" },
            { "recipe.flare", "Flare" },
            { "recipe.cell", "Lamp cell" },
            { "recipe.repair_kit", "Generator repair" },
            { "recipe.barricade_kit", "Reinforced wall" },
            { "recipe.radio_spare", "Radio spare" },
            { "lesson.0", "WASD move, mouse aim, left click fire. C crouch, Shift sprint." },
            { "lesson.1", "Fire the weapon in your hands. R reloads. 1-4 swaps." },
            { "lesson.2", "Crouch to cut your exposure. Noise still draws the horde." },
            { "lesson.3", "Kill and scavenge, then extract at the sanctuary gate." },
            { "lesson.4", "Tab opens the pack. If you fall, the next survivor takes the gate." },
            { "hint.move", "WASD moves. The mouse aims." },
            { "hint.fire", "Left click fires. R reloads." },
            { "hint.crouch", "Crouch cuts exposure. Noise still travels." },
            { "hint.loot", "Scrap and supplies go into the pack." },
            { "hint.pack", "Tab opens the pack. Use what you are carrying." },
            { "hint.reload", "An empty magazine does not fire. Reload before the click." },
            { "hint.flashlight", "The flashlight shows the street and shows you." },
            { "hint.medkit", "A medkit closes a bleed. It will not refill itself." },
            { "hint.sprint", "Sprint is loud and spends stamina." },
            { "hint.aim", "Aim tightens the shot, shortens the step, and narrows what you can see." },
            { "hint.extract", "The gate is the way home. Unfinished work will not let you through." },
            { "hint.weight", "The pack is near its limit. Drop or use something." },
            { "codex.zombie.walker.title", "Walker" },
            { "codex.zombie.walker.body", "Slow, loud, and enough of them to pin you. A scream pulls the ones you have not seen." },
            { "codex.zombie.runner.title", "Runner" },
            { "codex.zombie.runner.body", "Closes the gap with a lunge. Crouch and a corner buy you the reload." },
            { "codex.zombie.brute.title", "Brute" },
            { "codex.zombie.brute.body", "A charge that knocks you down. Barrels and a clear lane do more than a pistol." },
            { "codex.item.medkit.title", "Medkit" },
            { "codex.item.medkit.body", "Stops bleeding and puts health back. Q uses the one in your hands." },
            { "codex.module.generator.title", "Generator" },
            { "codex.module.generator.body", "Keeps the sanctuary lamps lit. It drinks fuel after dusk." },
            { "codex.module.barricade.title", "Barricade" },
            { "codex.module.barricade.body", "The night raid hits the nearest boards. A guard slows the damage." },
            { "codex.module.cot.title", "Medical cot" },
            { "codex.module.cot.body", "Rest and a medic close wounds faster than waiting the night out." },
            { "codex.faction.market.title", "Ash Market" },
            { "codex.faction.market.body", "The merchant trades medkits, rifle ammo, and water for camp scrap." },
            { "codex.mechanic.noise.title", "Noise" },
            { "codex.mechanic.noise.body", "Shots, sprints, and breaking barrels carry. Crouching cuts the footfall." },
            { "codex.mechanic.exposure.title", "Exposure" },
            { "codex.mechanic.exposure.body", "Lamplight and the flashlight make you easier to spot. Dark is cover." },
            { "codex.mechanic.infection.title", "Infection" },
            { "codex.mechanic.infection.body", "A dirty wound worsens until a medkit or the cot clears it." },
            { "codex.mechanic.extract.title", "Extraction" },
            { "codex.mechanic.extract.body", "Finish the quota, then stand in the sanctuary gate. The bag stays if you fall." }
        };

        private static readonly Dictionary<string, string> spanish = new Dictionary<string, string>
        {
            { "hud.expedition", "PUESTO CERO — EXPEDICIÓN" },
            { "hud.health", "Salud" },
            { "hud.stamina", "Aguante" },
            { "hud.lamp", "Linterna" },
            { "hud.extract", "Llega a la puerta del santuario para extraer" },
            { "hud.hunger", "Hambre" },
            { "hud.thirst", "Sed" },
            { "hud.fatigue", "Fatiga" },
            { "hud.hungry", "Hambriento" },
            { "hud.thirsty", "Sediento" },
            { "hud.exhausted", "Agotado" },
            { "hud.exposure", "Exposición" },
            { "hud.bleeding", "Sangrando" },
            { "hud.poison", "Veneno" },
            { "hud.adrenaline", "Adrenalina" },
            { "hud.burn", "En llamas" },
            { "burn.you", "Estás en llamas" },
            { "hud.infect1", "Infección I" },
            { "hud.infect2", "Infección II" },
            { "hud.infect3", "Infección III" },
            { "hud.watch", "Torre" },
            { "hud.kills", "Bajas" },
            { "hud.scrap", "Chatarra" },
            { "hud.tension", "Tensión" },
            { "hud.state.calm", "Calma" },
            { "hud.state.build", "Subida" },
            { "hud.state.peak", "Pico" },
            { "hud.state.relax", "Alivio" },
            { "hud.hold", "Mantén para extraer" },
            { "hud.hit.front", "Golpe de frente" },
            { "hud.hit.back", "Golpe por detrás" },
            { "hud.hit.left", "Golpe por la izquierda" },
            { "hud.hit.right", "Golpe por la derecha" },
            { "hud.noweapon", "Sin arma" },
            { "hud.reload", "recarga" },
            { "hud.low", "bajo" },
            { "hud.raid", "Asalto" },
            { "menu.pause", "PAUSA" },
            { "menu.resume", "Continuar" },
            { "menu.save", "Guardar" },
            { "menu.camp", "Santuario" },
            { "menu.settings", "Ajustes" },
            { "menu.main", "Menú principal" },
            { "menu.codex", "Códice" },
            { "menu.skip", "Saltar la lección" },
            { "menu.restart", "Reiniciar" },
            { "menu.leader", "LÍDER CAÍDO" },
            { "menu.choose", "Elige quién sale al amanecer." },
            { "menu.falls", "El puesto cae" },
            { "menu.holds", "EL PUESTO RESISTE" },
            { "menu.broadcast", "La emisión salió. La puerta puede quedar cerrada." },
            { "menu.enter", "Entrar al santuario" },
            { "menu.endless", "Seguir las noches" },
            { "menu.new", "Nuevo puesto" },
            { "menu.air", "La torre está al aire." },
            { "menu.supplies", "Los suministros volvieron a la puerta." },
            { "menu.next", "Siguiente:" },
            { "menu.names", "nombres en el muro." },
            { "menu.names_none", "Todos los nombres del registro se han ido." },
            { "menu.credits", "CRÉDITOS" },
            { "menu.brand", "Puesto Cero" },
            { "menu.blurb", "Un santuario, una calle, y quien siga en el tablero." },
            { "menu.tones", "Cada tono se genera en el juego." },
            { "menu.tones_n", "tonos generados" },
            { "menu.back", "Volver" },
            { "menu.title", "PUESTO CERO" },
            { "menu.version", "Versión" },
            { "menu.continue", "Continuar partida" },
            { "menu.saves", "Partidas" },
            { "slot.title", "PARTIDAS" },
            { "slot.word", "Ranura" },
            { "slot.day", "día" },
            { "slot.empty", "vacía" },
            { "slot.auto", "Autoguardado" },
            { "menu.street", "Volver a la calle" },
            { "menu.board", "Tablero local" },
            { "menu.board_empty", "Aún no hay partidas terminadas." },
            { "camp.title", "SANTUARIO" },
            { "result.title", "EXPEDICIÓN COMPLETA" },
            { "result.kills", "bajas" },
            { "result.scrap", "chatarra" },
            { "result.street", "Calle" },
            { "note.grief", "Una muerte en el campamento" },
            { "note.recovery", "Alguien se levanta" },
            { "note.fever", "Una fiebre se extendió" },
            { "note.stew", "La olla cocinó" },
            { "note.soak", "El patio está empapado" },
            { "note.friendship", "Nació una amistad" },
            { "note.argument", "Una discusión en la mesa" },
            { "note.breakdown", "Alguien se quebró" },
            { "note.celebration", "El campamento celebró" },
            { "gameover.title", "EL PUESTO CAE" },
            { "diff.scavenger", "Carroñero" },
            { "diff.survivor", "Superviviente" },
            { "diff.nightmare", "Pesadilla" },
            { "set.title", "AJUSTES" },
            { "set.shake", "Sacudida" },
            { "set.volume", "Volumen" },
            { "set.effects", "Efectos" },
            { "set.music", "Música" },
            { "set.ambience", "Ambiente" },
            { "set.ui", "Interfaz" },
            { "set.fov", "Campo visual" },
            { "set.text", "Texto" },
            { "set.hud", "HUD" },
            { "set.bright", "Brillo" },
            { "set.subs_on", "Subtítulos sí" },
            { "set.subs_off", "Subtítulos no" },
            { "set.flash_on", "Destellos sí" },
            { "set.flash_off", "Sin destellos" },
            { "set.color", "Modo daltónico" },
            { "set.vision0", "Apagado" },
            { "set.vision1", "Azul-amarillo" },
            { "set.vision2", "Mono" },
            { "set.quality", "Calidad:" },
            { "set.tier0", "Baja" },
            { "set.tier1", "Media" },
            { "set.tier2", "Alta" },
            { "set.tier3", "Ultra" },
            { "set.vsync_on", "Sincronía sí" },
            { "set.vsync_off", "Sincronía no" },
            { "set.frame", "Límite:" },
            { "set.resolution", "Resolución:" },
            { "set.aim_off", "Asistencia no" },
            { "set.aim_light", "Asistencia leve" },
            { "set.aim_strong", "Asistencia fuerte" },
            { "set.invert", "Mirar invertido" },
            { "set.look", "Mirar normal" },
            { "set.crouch_toggle", "Agacharse: alternar" },
            { "set.crouch_hold", "Agacharse: mantener" },
            { "set.sprint_toggle", "Correr: alternar" },
            { "set.sprint_hold", "Correr: mantener" },
            { "set.merciful", "Muerte clemente" },
            { "set.perma", "Muerte permanente" },
            { "set.next", "Siguiente:" },
            { "set.gore", "Gore:" },
            { "set.hit_on", "Impacto sí" },
            { "set.hit_off", "Impacto no" },
            { "set.num_on", "Números sí" },
            { "set.num_off", "Números no" },
            { "set.blur_on", "Desenfoque sí" },
            { "set.blur_off", "Desenfoque no" },
            { "set.window", "Ventana" },
            { "set.full", "Pantalla completa" },
            { "set.display", "Pantalla predeterminada" },
            { "set.keys", "Pulsa una acción y luego una tecla. Escape cancela." },
            { "bind.press", "Pulsa una tecla para" },
            { "bind.button", "Pulsa un botón para" },
            { "bind.pad", "Mando" },
            { "bind.Pause", "Pausa" },
            { "bind.Reload", "Recargar" },
            { "bind.Interact", "Interactuar" },
            { "bind.Medkit", "Botiquín" },
            { "bind.Flashlight", "Linterna" },
            { "bind.Crouch", "Agachar" },
            { "bind.Sprint", "Correr" },
            { "bind.Inventory", "Mochila" },
            { "bind.Throw", "Lanzar" },
            { "bind.Takedown", "Derribo" },
            { "bind.Build", "Construir" },
            { "bind.Wheel", "Rueda" },
            { "bind.Fire", "Disparar" },
            { "bind.Aim", "Apuntar" },
            { "bind.NextWeapon", "Siguiente" },
            { "bind.PrevWeapon", "Anterior" },
            { "bind.Dodge", "Esquivar" },
            { "set.reset_keys", "Restablecer teclas" },
            { "set.pad", "Pulsa una acción del mando y luego un botón. Escape cancela." },
            { "set.reset_pad", "Restablecer mando" },
            { "set.revert", "Revertir" },
            { "set.close", "Cerrar" },
            { "task.rest", "Descansar" },
            { "task.scavenge", "Rebuscar" },
            { "task.guard", "Vigilar" },
            { "task.cook", "Cocinar" },
            { "task.medic", "Curar" },
            { "task.build", "Construir" },
            { "task.clear", "Retirar" },
            { "task.lead", "Liderar" },
            { "task.fallen", "Caído" },
            { "task.quarantine", "Cuarentena" },
            { "camp.scrap", "Chatarra" },
            { "camp.food", "Comida" },
            { "camp.water", "Agua" },
            { "camp.cloth", "Tela" },
            { "camp.chem", "Quím" },
            { "camp.tape", "Cinta" },
            { "camp.raw", "Crudo" },
            { "camp.wear", "Cansancio" },
            { "camp.tired", "Agotado" },
            { "camp.rounds", "Balas" },
            { "camp.cell", "Pilas" },
            { "camp.press", "Prensadas" },
            { "camp.fuel", "Combustible" },
            { "camp.shots", "Disparos" },
            { "camp.bodies", "Cuerpos" },
            { "camp.lamps", "Las luces los descubren" },
            { "camp.warn", "La torre los ve" },
            { "camp.dusk", "El anochecer los trae" },
            { "camp.hit", "está herido" },
            { "camp.fell", "cayó" },
            { "camp.wiped", "El campamento cayó" },
            { "camp.spoiled", "Se derramaron las reservas" },
            { "camp.brute", "Un bruto está en las tablas" },
            { "camp.chew", "Muerden las tablas" },
            { "camp.line", "Los guardias sostienen la línea" },
            { "camp.sides", "lados" },
            { "camp.dark", "El patio se oscurece" },
            { "raid.tower", "Noche de emisión — aguanta la torre" },
            { "raid.from", "Incursión nocturna desde" },
            { "raid.gate", "la puerta" },
            { "raid.alley", "el callejón" },
            { "raid.yard", "el patio" },
            { "raid.fence", "la valla" },
            { "raid.broadcast", "La emisión salió" },
            { "raid.held", "La puerta aguantó" },
            { "raid.broke", "La incursión rompió las reservas" },
            { "raid.coming", "Vienen desde" },
            { "camp.haul", "Recoge el patio" },
            { "camp.mend", "Repara las tablas" },
            { "camp.morning", "Recoge el patio y repara las tablas" },
            { "camp.quiet", "Los muertos retroceden" },
            { "camp.slept", "Duermes" },
            { "camp.cot_sleep", "La cama sostiene la noche" },
            { "camp.gen_on", "Generador encendido" },
            { "camp.gen_off", "Generador apagado" },
            { "camp.morale", "Ánimo" },
            { "camp.memorial", "Muro memorial" },
            { "camp.caravan", "Caravana" },
            { "camp.away", "lejos" },
            { "camp.at_gate", "en la puerta" },
            { "camp.advance", "Avanzar guardia" },
            { "camp.raid_yes", "Esta noche es probable una incursión." },
            { "camp.raid_no", "La calle está quieta esta noche." },
            { "camp.endure", "Aguantar la noche" },
            { "camp.build", "Construir [B] y clic." },
            { "camp.barricade", "Barricada" },
            { "camp.cot", "Camilla" },
            { "camp.tower", "Torre" },
            { "camp.generator", "Generador" },
            { "camp.bench", "Banco" },
            { "camp.farm", "Huerto" },
            { "camp.purifier", "Purificadora" },
            { "camp.turret", "Torreta" },
            { "camp.turret_tier", "La torreta quiere un banco de nivel 2" },
            { "camp.spikes", "Pinchos" },
            { "camp.oil", "Aceite" },
            { "camp.raising", "Levantando" },
            { "camp.mend", "Reparar" },
            { "camp.crate", "Caja" },
            { "camp.lamp", "Foco" },
            { "camp.fire", "Fogata" },
            { "camp.room", "Almacén" },
            { "camp.sprout", "El huerto brota" },
            { "camp.post", "Puesto" },
            { "camp.craft", "Fabricar" },
            { "camp.bench_raise", "Subir el banco" },
            { "camp.bench_t2", "Banco T2" },
            { "camp.plans", "Planos" },
            { "camp.print", "Plano" },
            { "camp.radio_full", "La torre ya tiene sus piezas" },
            { "gate.tier", "Hace falta un banco de nivel 2" },
            { "gate.print", "Falta ese plano" },
            { "gate.gen", "Hace falta un generador dañado" },
            { "gate.bench", "Hace falta un banco" },
            { "gate.cot", "Hace falta una camilla" },
            { "gate.station", "Hace falta un puesto" },
            { "gate.medic", "Hace falta un médico de turno" },
            { "stall.bench", "Usar el banco" },
            { "stall.fire", "Cocinar y descansar" },
            { "stall.cot", "Tratar heridas" },
            { "stall.water", "Sacar agua" },
            { "stall.gen", "Cargar el generador" },
            { "stall.trade", "Comerciar" },
            { "stall.open", "Banco abierto — fabrica desde el campamento" },
            { "stall.wounds", "Heridas tratadas" },
            { "stall.drawn", "Agua recogida" },
            { "stall.fueled", "Generador cargado" },
            { "stall.scrap", "Hacen falta 4 de chatarra" },
            { "stall.short", "Faltan suministros" },
            { "stall.buy", "Comprar" },
            { "stall.sell", "Vender vendaje" },
            { "stall.deliver", "Entregar 4 botiquines" },
            { "stall.leave", "Salir" },
            { "stall.refuse", "no comercia" },
            { "stall.caravan", "La Caravana" },
            { "stall.militia", "Milicia de Hierro" },
            { "stall.clinic", "La Clínica" },
            { "stall.farmers", "Granjeros Libres" },
            { "quest.clinic", "La Clínica pide 4 botiquines" },
            { "quest.clinic_done", "Vendajes de campaña aprendidos" },
            { "quest.farmers", "Limpia un distrito para los granjeros" },
            { "quest.farmers_done", "Los granjeros recuerdan el nido" },
            { "quest.militia", "La Milicia de Hierro vende balas de rifle y cartuchos" },
            { "quest.caravan", "Extrae en un día de visita y la caravana paga" },
            { "quest.caravan_done", "Escolta cumplida" },
            { "gate.wall", "Hace falta una barricada dañada" },
            { "print.dressing", "Vendajes de campaña" },
            { "print.flare", "Bengala" },
            { "print.repair", "Reparación del generador" },
            { "print.wall", "Muro reforzado" },
            { "print.radio", "Repuesto de radio" },
            { "camp.radio", "Radio" },
            { "camp.reroll", "Otra calle" },
            { "camp.broadcast_holds", "La emisión sigue. Las noches continúan." },
            { "camp.tower_air", "La torre está al aire." },
            { "camp.broadcast", "Noche de emisión" },
            { "camp.tower_needs", "La torre necesita tres piezas de radio y un generador construido." },
            { "camp.district", "Distrito" },
            { "camp.clear", "despejado" },
            { "camp.part", "pieza" },
            { "camp.closed", "camino cerrado" },
            { "camp.fog", "Caminos sin mapa" },
            { "camp.trip", "Combustible gastado" },
            { "camp.searched", "registrado" },
            { "poi.cache", "Alijo" },
            { "poi.radio", "Pieza de radio" },
            { "sky.clear", "Despejado" },
            { "sky.fog", "Niebla" },
            { "sky.rain", "Lluvia" },
            { "sky.overcast", "Nublado" },
            { "sky.storm", "Tormenta" },
            { "camp.leave", "Salir al distrito" },
            { "camp.pack", "MOCHILA" },
            { "camp.weight", "Peso" },
            { "camp.pack_raise", "Mochila de campo" },
            { "camp.pack_t2", "La mochila carga 50" },
            { "camp.use", "Usar" },
            { "camp.info", "Info" },
            { "camp.belt", "Cinturón" },
            { "camp.drop", "Soltar" },
            { "camp.split", "Partir" },
            { "camp.container", "Contenedor" },
            { "camp.take_all", "Llevar todo" },
            { "camp.take", "Llevar" },
            { "camp.unknown", "Desconocido" },
            { "camp.unseen", "Aún no visto." },
            { "camp.seed", "semilla" },
            { "camp.opinion", "opinión" },
            { "camp.close", "cercano" },
            { "camp.gift", "Regalar comida" },
            { "camp.strip", "Desguazar arma" },
            { "camp.strip_none", "Guarda un arma" },
            { "camp.strip_full", "El almacén está lleno" },
            { "camp.strip_ok", "Piezas recuperadas" },
            { "camp.gift_none", "No hay comida para regalar" },
            { "camp.gift_ok", "Comida compartida" },
            { "bond.partner", "Pareja" },
            { "bond.friend", "Amigo" },
            { "bond.rival", "Rival" },
            { "camp.leads", "Lidera" },
            { "camp.codex", "Códice:" },
            { "camp.heavy", "La mochila pesa demasiado" },
            { "camp.picked", "Recogido" },
            { "unit.health", "salud" },
            { "unit.hunger", "hambre" },
            { "unit.thirst", "sed" },
            { "unit.rounds", "balas" },
            { "unit.cure", "Corta la infección" },
            { "unit.relief", "+20 de salud en 20 s" },
            { "unit.lure", "Atrae a los muertos" },
            { "unit.molotov", "Fuego al impacto" },
            { "unit.flare", "Atrae una búsqueda 20 s" },
            { "unit.cell", "Llena la linterna 60" },
            { "lamp.full", "La linterna está llena" },
            { "lamp.fit", "Pila puesta" },
            { "toss.none", "Nada que lanzar" },
            { "toss.take_bottle", "Coge la botella" },
            { "unit.pipe_bomb", "Estalla al impacto" },
            { "unit.cloth", "Vendajes y bombas" },
            { "unit.chemicals", "Munición y medicina" },
            { "unit.tape", "Sujeta un botiquín" },
            { "unit.material", "Chatarra del campamento" },
            { "item.medkit", "Botiquín" },
            { "item.bandage", "Vendaje" },
            { "item.antibiotics", "Antibióticos" },
            { "item.painkillers", "Analgésicos" },
            { "item.canned_food", "Comida enlatada" },
            { "item.raw_food", "Comida cruda" },
            { "item.print_flare", "Plano de bengala" },
            { "item.print_repair", "Plano de reparación" },
            { "item.print_wall", "Plano de muro" },
            { "item.print_radio", "Plano de radio" },
            { "item.water", "Botella de agua" },
            { "item.ammo_9mm", "Balas 9mm" },
            { "item.ammo_shells", "Cartuchos" },
            { "item.ammo_rifle", "Cargador de rifle" },
            { "item.ammo_smg", "Cargador de subfusil" },
            { "item.scrap", "Chatarra" },
            { "item.cloth", "Tela" },
            { "item.chemicals", "Químicos" },
            { "item.tape", "Cinta americana" },
            { "item.noise_lure", "Cebo de ruido" },
            { "item.molotov", "Molotov" },
            { "item.flare", "Bengala" },
            { "item.cell", "Pila" },
            { "item.pipe_bomb", "Bomba de tubo" },
            { "item.street_bottle", "Botella de la calle" },
            { "blurb.medkit", "Detiene la hemorragia y baja la fiebre." },
            { "blurb.bandage", "Detiene la hemorragia." },
            { "blurb.antibiotics", "Sirve antes de que la fiebre mate." },
            { "blurb.painkillers", "Un alivio lento, no una cura." },
            { "blurb.canned_food", "Pesa, y se conserva." },
            { "blurb.raw_food", "Poca si la comes. La fogata hace una comida." },
            { "blurb.water", "Una botella cubre unos diez minutos." },
            { "blurb.ammo_9mm", "Sirve para la pistola." },
            { "blurb.ammo_shells", "Sirve para la escopeta." },
            { "blurb.ammo_rifle", "Sirve para el rifle." },
            { "blurb.ammo_smg", "Sirve para el subfusil." },
            { "blurb.scrap", "El campamento gasta esto." },
            { "blurb.cloth", "Se vuelve vendajes en el santuario." },
            { "blurb.chemicals", "El banco pide una medida por cada tanda de balas." },
            { "blurb.tape", "Un rollo termina un botiquín." },
            { "blurb.noise_lure", "Lánzalo para apartar una horda de una puerta." },
            { "blurb.molotov", "Se rompe en fuego." },
            { "blurb.flare", "Arde veinte segundos y atrae una búsqueda." },
            { "blurb.pipe_bomb", "Una explosión corta y fuerte." },
            { "blurb.street_bottle", "Se rompe lo bastante fuerte para atraer a un grupo." },
            { "dist.ash_market", "Mercado de ceniza" },
            { "dist.rail_yard", "Patio ferroviario" },
            { "dist.old_hospital", "Hospital viejo" },
            { "dist.north_gate", "Puerta norte" },
            { "dist.commercial_strip", "Franja comercial" },
            { "dist.police_station", "Comisaría" },
            { "dist.water_plant", "Planta de agua" },
            { "dist.mall", "Centro comercial" },
            { "dist.highway_overpass", "Paso elevado" },
            { "dist.downtown_core", "Centro" },
            { "trait.steady", "Manos firmes" },
            { "trait.sleeper", "Duerme ligero" },
            { "trait.medic", "Médico de campo" },
            { "trait.scrounger", "Rebuscador" },
            { "trait.watchful", "Vigilante" },
            { "trait.volatile", "Volátil" },
            { "trait.glutton", "Glotón" },
            { "trait.engineer", "Ingeniero" },
            { "trait.cook", "Cocinero" },
            { "trait.sharp", "Tirador" },
            { "trait.brave", "Valiente" },
            { "trait.coward", "Cobarde" },
            { "trait.insomniac", "Insomne" },
            { "trait.optimist", "Optimista" },
            { "trait.loner", "Solitario" },
            { "trait.owl", "Noctámbulo" },
            { "barrel.hiss", "El barril silba" },
            { "ambush.warn", "La milicia tiene a los muertos esperando" },
            { "past.nurse", "Enfermera" },
            { "past.driver", "Conductor" },
            { "past.teacher", "Maestra" },
            { "past.mechanic", "Mecánico" },
            { "past.clerk", "Oficinista" },
            { "past.soldier", "Soldado" },
            { "mood.inspired", "Inspirado" },
            { "mood.steady", "Estable" },
            { "mood.depressed", "Deprimido" },
            { "mood.breakdown", "Colapso" },
            { "bill.craft", "Fabricar" },
            { "bill.scrap", "chatarra" },
            { "bill.cloth", "tela" },
            { "bill.chem", "quím" },
            { "bill.tape", "cinta" },
            { "clock.day", "Día" },
            { "clock.morning", "guardia de la mañana" },
            { "dose.kit", "Botiquín usado" },
            { "dose.hp", "PS" },
            { "dose.fail", "Los antibióticos no sirven" },
            { "dose.break", "La fiebre cede" },
            { "dose.spent", "Usado" },
            { "pack.fullbelt", "El cinturón está lleno" },
            { "pack.clear", "Cinturón vacío" },
            { "pack.belt", "Cinturón" },
            { "pack.dropped", "Soltado" },
            { "pack.pack", "La mochila está llena" },
            { "pack.poison", "Envenenado" },
            { "pack.made", "Fabricado" },
            { "loot.left", "Quedó botín atrás" },
            { "loot.open", "Contenedor abierto" },
            { "loot.empty", "Vacío" },
            { "gate.open", "Elige un distrito abierto" },
            { "gate.drag", "Arrastrado a la puerta" },
            { "gate.quota", "Objetivos sin cumplir" },
            { "gate.close", "Están demasiado cerca" },
            { "gate.road", "Ese camino sigue cerrado" },
            { "gate.radio", "Pieza de radio recuperada" },
            { "gate.out", "La emisión ya salió" },
            { "gate.extracted", "Extraído" },
            { "save.fail", "No se pudo guardar" },
            { "save.ok", "Partida guardada" },
            { "save.none", "No hay partida" },
            { "save.bad", "No se pudo leer la partida" },
            { "save.loaded", "Partida cargada" },
            { "save.auto", "Autoguardado cargado" },
            { "yard.mode", "Modo construir: pulsa el patio" },
            { "yard.off", "Modo construir apagado" },
            { "yard.facing", "Orientación" },
            { "yard.recovered", "Recuperados" },
            { "yard.scrap", "chatarra" },
            { "yard.taken", "Esa casilla está ocupada" },
            { "yard.need", "Hacen falta" },
            { "yard.needtail", "de chatarra" },
            { "yard.marked", "Sitio marcado" },
            { "yard.up", "en pie" },
            { "yard.patched", "Parcheado" },
            { "yard.mended", "Arreglado" },
            { "yard.gave", "Una barricada cedió" },
            { "yard.spikes", "Los pinchos se rompieron" },
            { "yard.oil", "El aceite prende" },
            { "yard.kind.barricade", "Barricada" },
            { "yard.kind.cot", "Camilla" },
            { "yard.kind.water", "Agua" },
            { "yard.kind.watchtower", "Torre" },
            { "yard.kind.generator", "Generador" },
            { "yard.kind.workbench", "Banco" },
            { "yard.kind.tradingpost", "Puesto" },
            { "yard.kind.farm", "Granja" },
            { "yard.kind.purifier", "Purificador" },
            { "yard.kind.turret", "Torreta" },
            { "yard.kind.spikes", "Pinchos" },
            { "yard.kind.oil", "Aceite" },
            { "yard.kind.crate", "Caja" },
            { "yard.kind.lamp", "Lámpara" },
            { "yard.kind.campfire", "Hoguera" },
            { "fight.start", "Derribo" },
            { "fight.slip", "El derribo falló" },
            { "fight.down", "Abajo" },
            { "fight.burst", "La bomba de tubo estalló" },
            { "fight.flare", "Bengala encendida" },
            { "fight.molotov", "Estalló el molotov" },
            { "fight.lure", "El cebo resonó" },
            { "fight.barrel", "El barril explotó" },
            { "fight.toxic", "Nube tóxica" },
            { "fight.oil", "Derrame de aceite" },
            { "pane.break", "El cristal se rompe" },
            { "pane.cut", "El cristal corta" },
            { "ash.air", "La ceniza flota en el aire" },
            { "home.bite", "La mordedura llegó a casa" },
            { "home.fever", "La fiebre llegó a casa" },
            { "hurt.bite", "Mordida" },
            { "hurt.fever", "Fiebre" },
            { "hurt.critical", "Crítica" },
            { "cot.bed", "En la camilla" },
            { "cot.well", "No está herido" },
            { "limp.bite", "La mordedura te frena" },
            { "limp.fever", "La fiebre te frena" },
            { "limp.critical", "Apenas puedes caminar" },
            { "ease.wound", "La herida cede" },
            { "ease.follow", "Alivia la mordedura" },
            { "rain.catch", "El colector atrapó la lluvia" },
            { "rain.storm", "El colector atrapó la tormenta" },
            { "tank.storm", "Una tormenta bebe el tanque" },
            { "yard.storm", "La tormenta gastó el patio" },
            { "yard.rain", "La lluvia gastó el patio" },
            { "swing.tired", "Demasiado cansado para cortar" },
            { "door.bar", "Atrancada" },
            { "door.hold", "La tranca aguanta" },
            { "door.gives", "La tranca cede" },
            { "door.rattle", "La tranca vibra" },
            { "door.shot", "El disparo pega en la tranca" },
            { "rack.wound", "La herida retrasa las manos" },
            { "post.bite", "La mordedura tira el tiro" },
            { "fight.held", "Ya llevas eso" },
            { "fight.took", "Tomaste" },
            { "fight.swap", "Armas cambiadas" },
            { "fight.boards", "Los tablones cedieron" },
            { "fight.roster", "La lista está llena" },
            { "fight.tower", "La torre no está lista" },
            { "fight.ledger", "No se pudo escribir el tablero" },
            { "fight.gun.pistol_9mm", "Pistola táctica 9mm" },
            { "fight.gun.shotgun_pump", "Escopeta Remington 870" },
            { "fight.gun.rifle_assault", "Rifle de asalto" },
            { "fight.gun.smg", "Subfusil compacto" },
            { "fight.gun.machete", "Machete de acero" },
            { "stall.wait", "No hay caravana hasta la próxima visita" },
            { "stall.shake", "El mercader niega con la cabeza" },
            { "stall.pack", "La mochila está llena" },
            { "stall.nobandage", "No hay vendaje para trocar" },
            { "stall.bartered", "Cambiaste un vendaje por" },
            { "stall.barterscrap", "chatarra" },
            { "stall.blueprint", "Plano de la Clínica: vendajes de campaña" },
            { "stall.nest", "Los Granjeros Libres recuerdan el nido limpio" },
            { "stall.through", "La Caravana logró pasar" },
            { "stall.sealed", "trato cerrado" },
            { "stall.gate", "está en la puerta" },
            { "ask.search", "Busca el contenedor" },
            { "ask.take", "Coge del contenedor" },
            { "ask.radio", "Coge la pieza de radio" },
            { "ask.cache", "Busca el alijo" },
            { "ask.gear", "Recupera el equipo" },
            { "ask.back", "De vuelta en la puerta" },
            { "ask.along", "Trae a" },
            { "ask.along2", "" },
            { "ask.togate", "Lleva a" },
            { "ask.togate2", "a la puerta" },
            { "ask.with", "va contigo" },
            { "ask.takes", "toma la puerta" },
            { "ask.survivor", "Superviviente" },
            { "ask.in", "Entra" },
            { "ask.out", "Sal" },
            { "ask.findcache", "Busca el alijo" },
            { "ask.findradio", "Busca la pieza de radio" },
            { "ask.searched", "Alijo registrado" },
            { "ask.stowed", "Pieza de radio guardada" },
            { "ask.stays", "se queda en el santuario" },
            { "ask.cry", "grita" },
            { "ask.swing", "golpea" },
            { "ask.bitten", "recibe una mordedura" },
            { "ask.drag", "apenas puede seguir" },
            { "ask.falls", "cae" },
            { "ask.kept", "Equipo recuperado" },
            { "ask.nameonly", "No queda más que el nombre" },
            { "door.inside", "Dentro" },
            { "door.street", "De vuelta en la calle" },
            { "craft.fitted", "colocado" },
            { "ask.brief.ash_market", "Saquea los puestos, vigila los callejones" },
            { "ask.brief.rail_yard", "Barriles y una manada bruta" },
            { "ask.brief.old_hospital", "Botiquines, salas infectadas" },
            { "ask.brief.north_gate", "La carretera al norte de la planta" },
            { "ask.brief.commercial_strip", "Las tiendas aún tienen latas al fondo" },
            { "ask.brief.police_station", "La armería está en el segundo piso" },
            { "ask.brief.water_plant", "Tanques, pasarelas y una valla larga" },
            { "ask.brief.mall", "El atrio está oscuro y lleno de ecos" },
            { "ask.brief.highway_overpass", "Coches apilados bajo el vano" },
            { "ask.brief.downtown_core", "El sitio de la torre queda tras la plaza" },
            { "load.boot", "DESPERTANDO LA PUERTA" },
            { "load.sanctuary", "EL SANTUARIO" },
            { "load.expedition", "AL DISTRITO" },
            { "load.results", "DE VUELTA DENTRO" },
            { "load.brand", "OUTPOST ZERO" },
            { "load.tip0", "El ruido llega más lejos que el disparo." },
            { "load.tip1", "Agáchate antes de disparar. La calle te oye de pie." },
            { "load.tip2", "Un bloque oscuro aún tiene ojos más allá de la farola." },
            { "load.tip3", "Extrae en la puerta del santuario. La bolsa no vuelve sola." },
            { "load.tip4", "Las barricadas caen si nadie está de guardia." },
            { "load.tip5", "La comida cocinada sube el ánimo. Una comida saltada no." },
            { "load.tip6", "El generador bebe combustible al anochecer." },
            { "load.tip7", "Tres piezas de radio y un generador abren la noche de emisión." },
            { "load.tip8", "Recarga antes de que el cargador haga clic vacío." },
            { "load.tip9", "Los barriles de aceite, tóxicos y de pólvora encadenan si los rompes." },
            { "load.tip10", "Un médico en el tablero cierra heridas entre guardias." },
            { "load.tip11", "Guarda antes de salir por la puerta." },
            { "tape.walker", "Caminante" },
            { "tape.runner", "Corredor" },
            { "tape.brute", "Bruto" },
            { "head.gate", "Puerta" },
            { "head.poi", "Punto" },
            { "head.behind", "detrás" },
            { "head.front", "frente" },
            { "head.back", "espalda" },
            { "head.left", "izquierda" },
            { "head.right", "derecha" },
            { "wheel.empty", "vacío" },
            { "board.held", "Aguantó" },
            { "board.fell", "Cayó" },
            { "board.day", "día" },
            { "board.kills", "bajas" },
            { "board.lost", "perdidos" },
            { "board.streets", "calles" },
            { "frame.auto", "Auto" },
            { "frame.30", "30 fps" },
            { "frame.60", "60 fps" },
            { "frame.120", "120 fps" },
            { "frame.uncapped", "Sin tope" },
            { "watch.title", "vigía" },
            { "watch.player", "Jugador" },
            { "watch.vfx", "efectos" },
            { "watch.peak", "pico" },
            { "watch.state.idle", "Quieto" },
            { "watch.state.wander", "Vagar" },
            { "watch.state.investigatenoise", "Investiga" },
            { "watch.state.searching", "Busca" },
            { "watch.state.chase", "Persecución" },
            { "watch.state.attack", "Ataque" },
            { "watch.state.dead", "Muerto" },
            { "bark.cant", "No puedo con esto." },
            { "bark.cook", "El fuego está listo." },
            { "bark.guard", "Vigilo la puerta." },
            { "bark.medic", "Quieto." },
            { "bark.scavenge", "Reviso los montones." },
            { "bark.build", "Lo levanto." },
            { "bark.clear", "Los retiro." },
            { "bark.hold", "Aguantaremos." },
            { "bark.rest", "Descansando." },
            { "bark.visit", "Me alegra verte." },
            { "task.visit", "Visita" },
            { "bark.tired", "Las piernas no dan más." },
            { "recipe.bandage", "Vendaje" },
            { "recipe.medkit", "Botiquín" },
            { "recipe.antibiotics", "Antibióticos" },
            { "recipe.painkillers", "Analgésicos" },
            { "recipe.ammo_9mm", "9mm (12)" },
            { "recipe.ammo_shells", "Cartuchos (6)" },
            { "recipe.ammo_rifle", "Cargador" },
            { "recipe.ammo_smg", "Cargador de subfusil" },
            { "recipe.noise_lure", "Cebo de ruido" },
            { "recipe.molotov", "Molotov" },
            { "recipe.pipe_bomb", "Bomba de tubo" },
            { "recipe.suppressor", "Silenciador" },
            { "recipe.rail", "Riel de linterna" },
            { "recipe.optic", "Mira" },
            { "recipe.extended_mag", "Cargador largo" },
            { "recipe.dressing", "Vendajes de campaña" },
            { "recipe.flare", "Bengala" },
            { "recipe.cell", "Pila" },
            { "recipe.repair_kit", "Reparación del generador" },
            { "recipe.barricade_kit", "Muro reforzado" },
            { "recipe.radio_spare", "Repuesto de radio" },
            { "lesson.0", "WASD mueve, el ratón apunta, clic izquierdo dispara. C agacha, Shift corre." },
            { "lesson.1", "Dispara el arma en las manos. R recarga. 1-4 cambia." },
            { "lesson.2", "Agacharse baja la exposición. El ruido sigue llamando a la horda." },
            { "lesson.3", "Mata y rebusca, luego extrae en la puerta del santuario." },
            { "lesson.4", "Tab abre la mochila. Si caes, el siguiente superviviente toma la puerta." },
            { "hint.move", "WASD mueve. El ratón apunta." },
            { "hint.fire", "El clic izquierdo dispara. R recarga." },
            { "hint.crouch", "Agacharse baja la exposición. El ruido viaja." },
            { "hint.loot", "La chatarra y los suministros van a la mochila." },
            { "hint.pack", "Tab abre la mochila. Usa lo que llevas." },
            { "hint.reload", "Un cargador vacío no dispara. Recarga antes del clic." },
            { "hint.flashlight", "La linterna muestra la calle y te muestra a ti." },
            { "hint.medkit", "Un botiquín cierra una hemorragia. No se rellena solo." },
            { "hint.sprint", "Correr hace ruido y gasta aguante." },
            { "hint.aim", "Apuntar aprieta el tiro, acorta el paso y estrecha lo que ves." },
            { "hint.extract", "La puerta es el camino a casa. El trabajo a medias no deja pasar." },
            { "hint.weight", "La mochila está al límite. Suelta o usa algo." },
            { "codex.zombie.walker.title", "Caminante" },
            { "codex.zombie.walker.body", "Lento, ruidoso, y bastan para inmovilizarte. Un grito llama a los que no ves." },
            { "codex.zombie.runner.title", "Corredor" },
            { "codex.zombie.runner.body", "Cierra la distancia con una embestida. Agacharse y una esquina dan la recarga." },
            { "codex.zombie.brute.title", "Bruto" },
            { "codex.zombie.brute.body", "Una carga que te tira. Los barriles y un pasillo claro valen más que una pistola." },
            { "codex.item.medkit.title", "Botiquín" },
            { "codex.item.medkit.body", "Detiene la hemorragia y devuelve salud. Q usa el que llevas." },
            { "codex.module.generator.title", "Generador" },
            { "codex.module.generator.body", "Mantiene las lámparas del santuario. Bebe combustible al anochecer." },
            { "codex.module.barricade.title", "Barricada" },
            { "codex.module.barricade.body", "La incursión nocturna golpea los tablones más cercanos. Un guardia frena el daño." },
            { "codex.module.cot.title", "Camilla" },
            { "codex.module.cot.body", "El descanso y un médico cierran heridas más rápido que esperar la noche." },
            { "codex.faction.market.title", "Mercado de ceniza" },
            { "codex.faction.market.body", "El mercader cambia botiquines, balas de rifle y agua por chatarra del campamento." },
            { "codex.mechanic.noise.title", "Ruido" },
            { "codex.mechanic.noise.body", "Los disparos, las carreras y los barriles rotos se oyen. Agacharse corta la pisada." },
            { "codex.mechanic.exposure.title", "Exposición" },
            { "codex.mechanic.exposure.body", "La luz de las farolas y la linterna te hacen fácil de ver. La oscuridad cubre." },
            { "codex.mechanic.infection.title", "Infección" },
            { "codex.mechanic.infection.body", "Una herida sucia empeora hasta que un botiquín o la camilla la limpia." },
            { "codex.mechanic.extract.title", "Extracción" },
            { "codex.mechanic.extract.body", "Cumple la cuota y quédate en la puerta del santuario. La bolsa se queda si caes." }
        };

        public static string T(string key)
        {
            string language = SettingsService.Instance != null ? SettingsService.Instance.Language : "en";
            return T(key, language);
        }

        public static string T(string key, string language)
        {
            var table = language == "es" ? spanish : english;
            return table.TryGetValue(key, out var value) ? value : key;
        }

        public static string Difficulty(int stored)
        {
            int level = stored <= 0 ? 2 : stored >= 3 ? 3 : stored;
            if (level == 1) return T("diff.scavenger");
            if (level == 3) return T("diff.nightmare");
            return T("diff.survivor");
        }

        public static string Item(string id)
        {
            return Pick("item." + (id ?? ""), id ?? "");
        }

        public static string Item(string id, string language)
        {
            return Pick("item." + (id ?? ""), id ?? "", language);
        }

        public static string District(string id)
        {
            return Pick("dist." + (id ?? ""), id ?? "");
        }

        public static string District(string id, string language)
        {
            return Pick("dist." + (id ?? ""), id ?? "", language);
        }

        public static string Task(string id)
        {
            return Task(id, null);
        }

        public static string Task(string id, string language)
        {
            if (string.IsNullOrEmpty(id)) return "";
            return Pick("task." + id.ToLowerInvariant(), id, language);
        }

        public static string Trait(string trait)
        {
            string key = trait == "Steady Hands" ? "trait.steady"
                : trait == "Light Sleeper" ? "trait.sleeper"
                : trait == "Field Medic" ? "trait.medic"
                : trait == "Scrounger" ? "trait.scrounger"
                : trait == "Watchful" ? "trait.watchful"
                : trait == "Volatile" ? "trait.volatile"
                : trait == "Glutton" ? "trait.glutton"
                : trait == "Engineer" ? "trait.engineer"
                : trait == "Cook" ? "trait.cook"
                : trait == "Sharpshooter" ? "trait.sharp"
                : trait == "Brave" ? "trait.brave"
                : trait == "Cowardly" ? "trait.coward"
                : trait == "Insomniac" ? "trait.insomniac"
                : trait == "Optimist" ? "trait.optimist"
                : trait == "Loner" ? "trait.loner"
                : trait == "Night Owl" ? "trait.owl"
                : "";
            if (key.Length == 0) return trait ?? "";
            return Pick(key, trait);
        }

        public static string Mood(string mood)
        {
            return Mood(mood, null);
        }

        public static string Mood(string mood, string language)
        {
            if (string.IsNullOrEmpty(mood)) return "";
            return Pick("mood." + mood.ToLowerInvariant(), mood, language);
        }

        public static string Bark(string action, float morale)
        {
            return Bark(action, morale, 0f);
        }

        public static string Bark(string action, float morale, float fatigue)
        {
            string key = morale < 10f ? "bark.cant"
                : action == "Visit" ? "bark.visit"
                : action == "Rest" && OutpostZero.Player.NeedsPressure.Tired(fatigue) ? "bark.tired"
                : action == "Cook" ? "bark.cook"
                : action == "Guard" ? "bark.guard"
                : action == "Medic" ? "bark.medic"
                : action == "Scavenge" ? "bark.scavenge"
                : action == "Build" ? "bark.build"
                : action == "Clear" ? "bark.clear"
                : morale > 70f ? "bark.hold"
                : "bark.rest";
            return Pick(key, OutpostZero.Colony.CampRoutine.Bark(action, morale, fatigue));
        }

        public static string Recipe(string id, string fallback)
        {
            return Pick("recipe." + (id ?? ""), fallback ?? "");
        }

        public static string EntryTitle(string id, string fallback)
        {
            return Pick("codex." + id + ".title", fallback ?? "");
        }

        public static string EntryBody(string id, string fallback)
        {
            return Pick("codex." + id + ".body", fallback ?? "");
        }

        public static string Hint(string id, string fallback)
        {
            return Pick(id ?? "", fallback ?? "");
        }

        public static string Lesson(int index, string fallback)
        {
            return Pick("lesson." + index, fallback ?? "");
        }

        private static string Pick(string key, string fallback)
        {
            return Pick(key, fallback, null);
        }

        private static string Pick(string key, string fallback, string language)
        {
            string line = language == null ? T(key) : T(key, language);
            return line == key ? fallback : line;
        }
    }
}
