<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><AssemblyName>OutpostZero.Editor</AssemblyName><EditorRefs>true</EditorRefs><ExtraDefines>UNITY_EDITOR</ExtraDefines></PropertyGroup>
  <Import Project="../packages.props" />
  <ItemGroup>
    <Compile Include="$(RepoRoot)/Assets/Scripts/Editor/**/*.cs" />
    <ProjectReference Include="../GameEditor/GameEditor.csproj" />
  </ItemGroup>
</Project>
